// Gen_TabIO - ExportManager.js
// Gestion centralisee de l'export des fichiers
// Formats : Excel (.csv), Text (.txt), TIA Portal (.xml), Step7 Manager (.SDF)

class ExportManager {
    constructor() {
        this.formats = {
            'excel': {
                id: 'excel',
                name: 'Excel',
                ext: 'csv',
                converter: 'toCSV',
                wrapper: function(lines, views) { return ExportManager.wrapCSV(lines, views); }
            },
            'txt': {
                id: 'txt',
                name: 'Text',
                ext: 'txt',
                converter: 'toTXT',
                wrapper: function(lines, views) { return ExportManager.wrapTXT(lines, views); }
            },
            'tia-portal': {
                id: 'tia-portal',
                name: 'TIA Portal',
                ext: 'xml',
                converter: 'toTIA_XML',
                wrapper: function(lines, views) { return ExportManager.wrapTIA_XML(lines, views); }
            },
            'step7': {
                id: 'step7',
                name: 'Step7 Manager',
                ext: 'SDF',
                converter: 'toStep7_SDF',
                wrapper: function(lines, views) { return ExportManager.wrapStep7_SDF(lines, views); }
            }
        };
    }

    getAvailableFormats() {
        return Object.values(this.formats).map(function(f) {
            return { id: f.id, name: f.name, ext: f.ext };
        });
    }

    getFormatInfo(formatId) {
        return this.formats[formatId] || null;
    }

    generate(formatId, addrViews) {
        var format = this.formats[formatId];
        if (!format) {
            console.warn('[ExportManager] Format inconnu: ' + formatId);
            return null;
        }

        if (!addrViews || addrViews.length === 0) {
            return '';
        }

        var lines = addrViews.map(function(view) {
            if (typeof view[format.converter] === 'function') {
                return view[format.converter]();
            }
            console.warn('[ExportManager] Methode manquante: ' + format.converter);
            return '';
        });

        return format.wrapper(lines, addrViews);
    }

    download(content, filename) {
        var blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
        var url = URL.createObjectURL(blob);
        var a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
}


// ============================================================
// Wrappers statiques
// ============================================================

/**
 * Wrapper CSV : en-tete avec ';'
 */
ExportManager.wrapCSV = function(lines, addrViews) {
    var header = 'Position;Categorie;Nom;Adresse;Commentaire';
    return header + '\n' + lines.join('\n');
};

/**
 * Wrapper TXT : format texte lisible
 */
ExportManager.wrapTXT = function(lines, addrViews) {
    var sep = '='.repeat(85);
    var thin = '-'.repeat(85);
    var inCount  = addrViews.filter(function(v) { return v.category === 'INPUT'; }).length;
    var outCount = addrViews.filter(function(v) { return v.category === 'OUTPUT'; }).length;
    var ts = new Date().toLocaleString();

    return sep + '\n' +
           '  Gen_TabIO - Address Table Export\n' +
           sep + '\n' +
           '  Generated: ' + ts + '\n' +
           '  Total: ' + addrViews.length + ' addresses (INPUT: ' + inCount + ', OUTPUT: ' + outCount + ')\n' +
           thin + '\n' +
           '  Pos | Cat    | Nom                  | Adresse         | Commentaire\n' +
           thin + '\n' +
           lines.map(function(l) { return '  ' + l; }).join('\n') + '\n' +
           thin + '\n' +
           '  Generated by Gen_TabIO\n' +
           sep;
};

/**
 * Wrapper TIA Portal XML conforme
 *
 * <?xml version='1.0' encoding='utf-8'?>
 * <Tagtable name='Default tag table'>
 *   <Tag ... addr='%I0.0'>nom</Tag>
 * </Tagtable>
 */
ExportManager.wrapTIA_XML = function(lines, addrViews) {
    return "<?xml version='1.0' encoding='utf-8'?>\n" +
           "<Tagtable name='Default tag table'>\n" +
           lines.join('\n') + '\n' +
           '</Tagtable>';
};

/**
 * Wrapper Step7 SDF : lignes brutes, pas d'en-tete
 */
ExportManager.wrapStep7_SDF = function(lines, addrViews) {
    return lines.join('\n');
};


// Instance globale
window.exportManager = new ExportManager();
